apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bgg-stats
  name: bgg-stats
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bgg-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg-stats
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgg-stats
    spec:
      containers:
      - image: gcr.io/mm-bgg-stats/bgg-stats:latest
        imagePullPolicy: IfNotPresent
        name: bgg-stats
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
