apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-18T20:48:07Z"
  generation: 1
  labels:
    app: bgg-stats
  name: bgg-stats
  namespace: default
  resourceVersion: "1558"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bgg-stats
  uid: b98149a6-0a44-11ea-ac92-42010a8a0081
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bgg-stats
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgg-stats
    spec:
      containers:
      - image: gcr.io/mm-bgg-stats/bgg-stats:v1
        imagePullPolicy: IfNotPresent
        name: bgg-stats
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-18T20:49:04Z"
    lastUpdateTime: "2019-11-18T20:49:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-11-18T20:48:07Z"
    lastUpdateTime: "2019-11-18T20:49:04Z"
    message: ReplicaSet "bgg-stats-bd4d9c95f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
