apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - image: gcr.io/mm-bgg-stats/bgg-stats:latest
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 5000
          protocol: TCP
